export const predefinedChallenges = [
  //  Run
  {
    id: "run_100m_sprint",
    name: "100 Meter Sprint",
    duration: "10 minutes",
    distance: "100 meters",
    reward: "200 XP",
    status: "Active",
    category: "Run",
  },
  {
    id: "run_10mile_24hr",
    name: "10 Mile Run in 24 hrs",
    duration: "24 hours",
    distance: "10 miles",
    reward: "500 XP",
    status: "Active",
    category: "Run",
  },
  {
    id: "run_5k_daily",
    name: "5K-a-Day for 7 Days",
    duration: "7 days",
    distance: "5 kilometers daily",
    reward: "1000 XP",
    status: "Active",
    category: "Run",
  },
  {
    id: "run_hill_sprint",
    name: "12 Mile Hill Sprint",
    duration: "30 minutes",
    distance: "12 miles",
    reward: "600 XP",
    status: "Active",
    category: "Run",
  },
  {
    id: "run_treadmill_marathon",
    name: "Treadmill Marathon",
    duration: "3 hours",
    distance: "26.2 miles",
    reward: "750 XP",
    status: "Active",
    category: "Run",
  },

  //  Walk
  {
    id: "walk_5k",
    name: "5K Walk Challenge",
    duration: "1 hour",
    distance: "5 kilometers",
    reward: "250 XP",
    status: "Active",
    category: "Walk",
  },
  {
    id: "walk_1mile_daily",
    name: "Walk 1 Mile Daily",
    duration: "7 days",
    distance: "1 mile daily",
    reward: "300 XP",
    status: "Active",
    category: "Walk",
  },
  {
    id: "walk_weekend_loop",
    name: "Weekend Loop Walk",
    duration: "2 days",
    distance: "10 kilometers",
    reward: "400 XP",
    status: "Active",
    category: "Walk",
  },
  {
    id: "walk_evening_stroll",
    name: "Evening Stroll Challenge",
    duration: "5 days",
    distance: "2 kilometers daily",
    reward: "350 XP",
    status: "Active",
    category: "Walk",
  },
  {
    id: "walk_marathon_week",
    name: "Marathon Distance in a Week",
    duration: "7 days",
    distance: "42.2 kilometers total",
    reward: "700 XP",
    status: "Active",
    category: "Walk",
  },

  //  Yoga
  {
    id: "yoga_morning_flow",
    name: "Morning Yoga Flow",
    duration: "30 minutes",
    distance: "",
    reward: "300 XP",
    status: "Active",
    category: "Yoga",
  },
  {
    id: "yoga_sunset_stretch",
    name: "Sunset Yoga Stretch",
    duration: "45 minutes",
    distance: "",
    reward: "350 XP",
    status: "Active",
    category: "Yoga",
  },
  {
    id: "yoga_7_day_challenge",
    name: "7-Day Yoga Challenge",
    duration: "7 days",
    distance: "",
    reward: "600 XP",
    status: "Active",
    category: "Yoga",
  },
  {
    id: "yoga_core_strength",
    name: "Yoga for Core Strength",
    duration: "40 minutes",
    distance: "",
    reward: "400 XP",
    status: "Active",
    category: "Yoga",
  },
  {
    id: "yoga_flexibility_focus",
    name: "Flexibility Focus Series",
    duration: "5 days",
    distance: "",
    reward: "500 XP",
    status: "Active",
    category: "Yoga",
  },

  // Lifting
  {
    id: "lift_deadlift500",
    name: "500 Rep Deadlift Challenge",
    duration: "1 week",
    distance: "",
    reward: "800 XP",
    status: "Active",
    category: "Lifting",
  },
  {
    id: "lift_push_pull_legs",
    name: "Push-Pull-Legs Week",
    duration: "7 days",
    distance: "",
    reward: "700 XP",
    status: "Active",
    category: "Lifting",
  },
  {
    id: "lift_squat_challenge",
    name: "Squat Everyday Challenge",
    duration: "5 days",
    distance: "",
    reward: "650 XP",
    status: "Active",
    category: "Lifting",
  },
  {
    id: "lift_upperbody_focus",
    name: "Upper Body Focus",
    duration: "3 days",
    distance: "",
    reward: "500 XP",
    status: "Active",
    category: "Lifting",
  },
  {
    id: "lift_100_pushups",
    name: "100 Push-Ups a Day",
    duration: "5 days",
    distance: "",
    reward: "550 XP",
    status: "Active",
    category: "Lifting",
  },

  //  Cycling
  {
    id: "cycle_20mile_sprint",
    name: "20 Mile Cycling Sprint",
    duration: "1 day",
    distance: "20 miles",
    reward: "500 XP",
    status: "Active",
    category: "Cycling",
  },
  {
    id: "cycle_100mile",
    name: "100 Mile Cycle",
    duration: "3 days",
    distance: "100 miles",
    reward: "1000 XP",
    status: "Active",
    category: "Cycling",
  },
  {
    id: "cycle_30min_daily",
    name: "30 Min Ride Daily",
    duration: "7 days",
    distance: "",
    reward: "600 XP",
    status: "Active",
    category: "Cycling",
  },
  {
    id: "cycle_city_loop",
    name: "City Loop Ride",
    duration: "45 minutes",
    distance: "15 miles",
    reward: "450 XP",
    status: "Active",
    category: "Cycling",
  },
  {
    id: "cycle_climb_challenge",
    name: "Hill Climb Challenge",
    duration: "2 days",
    distance: "30 miles",
    reward: "700 XP",
    status: "Active",
    category: "Cycling",
  },
];
