export const predefinedChallenges = [
  {
    id: "challenge1",
    name: "100 Meter Race",
    category: "Run",
    duration: "10 minutes",
    distance: "100 meters",
    reward: "200 XP",
    status: "Active",
    month: "March",
    participants: [],
    progress: {},
  },
  {
    id: "challenge2",
    name: "10 Mile Run in 24 hrs",
    category: "Run",
    duration: "24 hours",
    distance: "10 miles",
    reward: "500 XP",
    status: "Active",
    month: "March",
    participants: [],
    progress: {},
  },
  {
    id: "challenge3",
    name: "12 Mile Hill Sprint",
    category: "Run",
    duration: "30 minutes",
    distance: "12 miles",
    reward: "600 XP",
    status: "Active",
    month: "March",
    participants: [],
    progress: {},
  },
  {
    id: "challenge4",
    name: "5K-a-Day for 7 Days",
    category: "Run",
    duration: "7 days",
    distance: "5 kilometers daily",
    reward: "1,000 XP",
    status: "Active",
    month: "March",
    participants: [],
    progress: {},
  },
  {
    id: "challenge5",
    name: "Treadmill Marathon",
    category: "Run",
    duration: "Unlimited",
    distance: "26.2 miles",
    reward: "750 XP",
    status: "Active",
    month: "March",
    participants: [],
    progress: {},
  },
];
