name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          cd ios
          pod install

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace FitVibe.xcworkspace -scheme FitVibe -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' clean build

      - name: Run iOS tests
        run: |
          cd ios
          xcodebuild test -workspace FitVibe.xcworkspace -scheme FitVibe -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
